Issue errors
konoongg/pg_redis_proxy pull request #1
Opened 2024-07-26 17:47 UTC by CaptainCuriousity

Added proxy configuration, basic error handling also created.

2024-07-27 12:12 UTC, konoongg requested changes

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +const ProxyConfiguration DEFAULT_CONFIG = {6379, 512, 16, LOG_NOTICE, false, NULL, NULL, 0, NULL};
сюда бы добавить комментарий, что это за параметры

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
>  int
приведи все к формату, чтобы вся сигнатура была в одной строчке, в остальных местах писать не буду, но так надо везде

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +    ereport(LOG, errmsg("start init table"));
это скорее debug уровень

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +init_configuration() {
в скобочках надо указать void, в этом стандарте си это обязательно

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +    char parameter_name[64], parameter_value[256], line[1024];
почему именно такие значения у массивов?

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +        if (init_config_loglevel >= LOG_WARNING) ereport(ERROR, errmsg("Couldn't start loading configuration from file redis.conf: %s", error_message));
а где скобочки у  if? тут же две строчки к нему и вообще всегда скобочки пиши

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +        if (init_config_loglevel >= LOG_WARNING) ereport(ERROR, errmsg("Couldn't start loading configuration from file redis.conf: %s", error_message));
и вообще не очень понимаю смысла этого if, он зачем нужен? зачем кидать ошибку, если урвоень логирования больше ворнинга?

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +    while (fscanf(config_file, "%[^\n]\n", line) != EOF) {
зачем конфиг считывать построчно? какой у него размер? нельзя сразу весь считать?

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +        if (init_config_loglevel >= LOG_VERBOSE)
это явно debug

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +        if (init_config_loglevel >= LOG_VERBOSE)
да и у самого постгреса есть конфиг, в котором настраивается логирование, зачем нам еще обрабатывать логирование редиса? получается, что в настройках постгерса может стоять, что только ошибки, а в редисе все, но пользователь будет получать только ошибки, нам не нужна поддержка редисовского логирвоания

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +            if (init_config_loglevel >= LOG_WARNING)
вообще не понимаю этого if, у нас произошла ошибка, это нештатная ситуация, вопрос, нужно ли тут вообще продолжать парсить конфиг? мне кажется, в таком случае лучше вообще прекращать парсинг и писать пользователю ошибку, что конфиг неправильный

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +            integer_parameter_value = atoi(parameter_value);
не обрабатываются ошибки, я нашел вот такое

Важно отметить, что atoi не различает случаи, когда строка действительно представляет число 0 и когда строка не содержит числа. Для более точной обработки ошибок рекомендуется использовать функцию strtol, которая позволяет определить, было ли успешное преобразование и какой остаток строки не был обработан.

это относится ков сему, где есть atoi

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +            char* raw_bind = (char*)malloc(1024 * sizeof(char));
что такое raw_bind нужен коммент или ренейминг

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +            if (init_config_loglevel >= LOG_VERBOSE)
все ещен е понимаю идею проверки уровня логирвоания

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +        else if (!strcmp(parameter_name, "loglevel")) { // by default, it stays notice
писал про то, что поддержка этого параметра фактически бессмыслена

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +            if (init_config_loglevel >= LOG_NOTICE)
и если уровень логирования устанавливается только здесь, то как работает логирвоания в предыдущих функциях?

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +            SnapshotData* save_data = (SnapshotData*)malloc(sizeof(SnapshotData) * 16); // no more that 16 supported
у нас нет снапшотов, нам нужно только время, у нас снапшоты делаются в бд

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +            bool is_cur_time = true; // firstly time, then actions needed, then repeat
зачем нужна эта переменная?

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +            bool is_cur_time = true; // firstly time, then actions needed, then repeat
я про is_cur_time

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +            char* token;
token это что?

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +                    current_data.saving_period = atoi(token);
какие парметры save может принимать кроме частоты? я так понимаю, ты их тут парсишь, напиши это комментарием

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.h
> +struct SnapshotData {
за что отвечает actions_needed?

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.h
>  struct ProxyConfiguration {
напиши комментарий, за что отвечает каждый парамметр

2024-07-27 12:12 UTC, konoongg commented on configure_proxy/configure_proxy.h
> +extern ProxyConfiguration config;
зачем extern?

2024-07-27 12:12 UTC, konoongg commented on postgres_reqv_converter/postgres_reqv_converter.c
> +    ereport(LOG, errmsg("RESULT CreateStr: %s ", *answer));
вот эти логи бы пометить как  debug

2024-07-27 12:12 UTC, konoongg commented on postgres_reqv_converter/postgres_reqv_converter.c
> +    ereport(LOG, errmsg("RESULT CreateStr: %s ", *answer));
там надо посмотреть, большую часть сделать debug

2024-07-27 12:12 UTC, konoongg commented on postgres_reqv_converter/postgres_reqv_converter.c
> +int
писал уже про формат сигнатуры

2024-07-27 12:12 UTC, konoongg commented on postgres_reqv_converter/postgres_reqv_converter.c
> +int
тут бы комментарий про формат ошибок, можно просто из доки

2024-07-27 12:12 UTC, konoongg commented on postgres_reqv_converter/postgres_reqv_converter.c
> +    (*answer)[(*size_answer) - 1] = '\n';
memcpy(*answer + *size_answer - 2, "\r\n", 2); тут тоже так можно сделать

2024-07-27 12:12 UTC, konoongg commented on postgres_reqv_converter/postgres_reqv_converter.c
> +    ereport(NOTICE, errmsg("Start CreateErr: %s ", reqv));
чем урвоень noticeотличается от debug

2024-07-27 12:12 UTC, konoongg commented on proxy_hash/proxy_hash.c
> +        ereport(LOG, (errmsg("get result: %s", (char*)result)));
это debug, больше писать не буду, ное сли ты раскоментил, то там надо в большинстве случаем сделать debug

2024-07-27 12:12 UTC, konoongg commented on proxy_hash/proxy_hash.c
> +        ereport(LOG, (errmsg("get result: %s", (char*)result)));
а зачем ыт их раскоммнетил вообще?

2024-07-27 12:12 UTC, konoongg commented on redis_proxy.c
> +    init_configuration();
а она не можетв ернуть какие-то ошибки или тп?

2024-07-27 12:12 UTC, konoongg commented on redis_proxy.c
> +    if (config.loglevel == LOG_NOTHING)
уже писал, почему это не оч крутая идея

2024-07-27 12:12 UTC, konoongg commented on redis_proxy.c
> +    if (config.loglevel == LOG_NOTHING)
да и не очень пкоа понимаю, где это используется

2024-07-27 12:12 UTC, konoongg commented on redis_reqv_converter/redis_reqv_converter.c
> +        if (config.loglevel >= LOG_DEBUG) ereport(ERROR, errmsg("IN process_get: GET err with key: %s", key));
так if писать нельзя, где фигурные скобочки

2024-07-27 12:12 UTC, konoongg commented on redis_reqv_converter/redis_reqv_converter.c
> +// error sizes are different, but in general case they are not larger than 256.
там есть еще понятие bulk err но мы с ним не работаем

2024-07-27 12:12 UTC, konoongg commented on redis_reqv_converter/redis_reqv_converter.c
> +// error sizes are different, but in general case they are not larger than 256.
256 тогда лучше вынести в  какую-нибудь коснтанту, а то просто число из неоткуда для человека, который его увидит

2024-07-27 12:12 UTC, konoongg commented on t/001_whole_test.pl
>      $request = "*2\r\n\$3\r\nDEL\r\n\$3\r\nkey\r\n";
надо тогда добавить/раскоментить тесты на ошибки

2024-07-27 12:12 UTC, konoongg commented on work_with_db/work_with_db.c
> +    // if (config.loglevel >= LOG_VERBOSE) ereport(LOG, errmsg("start work with db"));
ну про if думаю ты понял, но  и про систему логирования тоже уже писал

2024-07-28 17:31 UTC, CaptainCuriousity commented on configure_proxy/configure_proxy.c
> +    char parameter_name[64], parameter_value[256], line[1024];
Мне так захотелось.

2024-07-28 17:43 UTC, CaptainCuriousity commented on redis_proxy.c
> +    if (config.loglevel == LOG_NOTHING)
Конкретно в этой функции используется свой уровень логгирования. Реализовано было по той причине, что ты ранее указал, что реализовать это надо.

2024-07-28 17:44 UTC, CaptainCuriousity commented on redis_reqv_converter/redis_reqv_converter.c
> +// error sizes are different, but in general case they are not larger than 256.
У нас и так везде magic constants, но окэй...

2024-07-28 18:11 UTC, CaptainCuriousity commented on t/001_whole_test.pl
>      $request = "*2\r\n\$3\r\nDEL\r\n\$3\r\nkey\r\n";
Раскомментил старые тесты, но сделал их проще.

2024-07-29 15:02 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +    char parameter_name[64], parameter_value[256], line[1024];
а динамически выделять нельзя?

2024-07-29 15:03 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +        if (init_config_loglevel >= LOG_WARNING) ereport(ERROR, errmsg("Couldn't start loading configuration from file redis.conf: %s", error_message));
ну скобочки да, но про логи я так и не понял, зачем они нужны

2024-07-29 15:07 UTC, konoongg commented on configure_proxy/configure_proxy.c
> +            bool is_cur_time = true; // firstly time, then actions needed, then repeat
все еще бы не помешал комменатрий

2024-07-29 15:09 UTC, konoongg commented on configure_proxy/configure_proxy.h
> +extern ProxyConfiguration config;
так он нужен или нет?

2024-07-29 15:11 UTC, konoongg commented on redis_proxy.c
> +    if (config.loglevel == LOG_NOTHING)
нет, свое логирование не нужно, оно есть в псотгресе

2024-07-29 15:12 UTC, konoongg commented on redis_reqv_converter/redis_reqv_converter.c
> +// error sizes are different, but in general case they are not larger than 256.
надо избавляться от этого

2024-07-29 15:41 UTC, konoongg requested changes

2024-07-29 15:41 UTC, konoongg commented on work_with_db/work_with_db.c
>      if (!strcmp(PQgetvalue(res, 0, 0), "f"))
зачем этот if?

2024-07-30 03:01 UTC, CaptainCuriousity commented on redis_proxy.c
> +    if (config.loglevel == LOG_NOTHING)
Удалю тогда.

2024-07-30 05:13 UTC, CaptainCuriousity commented on work_with_db/work_with_db.c
>      if (!strcmp(PQgetvalue(res, 0, 0), "f"))
f=false, если мы получили такой ответ, то лишняя единица не записывается в результат выполнения команды del.

2024-07-30 16:03 UTC, konoongg commented on work_with_db/work_with_db.c
>      if (!strcmp(PQgetvalue(res, 0, 0), "f"))
PQgetvalue возвращает значение, которое находится в 0 строке, в 0 столбце,strcmp сравнивает строки, почему стркоа в таблице должна быть  равна f?

2024-07-30 16:54 UTC, CaptainCuriousity commented on work_with_db/work_with_db.c
>      if (!strcmp(PQgetvalue(res, 0, 0), "f"))
Это означает, что элемента не существует

2024-07-31 08:45 UTC, CaptainCuriousity commented on configure_proxy/configure_proxy.h
> +extern ProxyConfiguration config;
extern Нужен для того, чтобы переменная config была видна отовсюду. Она расширяет область видимости. Если надо - могу запилить какой-нибудь "метод" get_configuration, чтобы такой "супер-глобальной" переменной не было.

2024-07-31 08:46 UTC, CaptainCuriousity commented on configure_proxy/configure_proxy.c
> +            integer_parameter_value = atoi(parameter_value);
Сделано

2024-07-31 08:47 UTC, CaptainCuriousity commented on configure_proxy/configure_proxy.c
> +            SnapshotData* save_data = (SnapshotData*)malloc(sizeof(SnapshotData) * 16); // no more that 16 supported
Снапшотом в нашей интерпретации будет сохранение из кэша в БД, а не из оперативки на жёсткий диск

2024-07-31 08:47 UTC, CaptainCuriousity commented on configure_proxy/configure_proxy.c
> +            bool is_cur_time = true; // firstly time, then actions needed, then repeat
Комментарий написал. Это флаг, нужный для правильного парса параметра save, в оригинале он представлен в таком виде:

2024-07-31 08:49 UTC, CaptainCuriousity commented on configure_proxy/configure_proxy.c
> +            bool is_cur_time = true; // firstly time, then actions needed, then repeat
save 3600 1 300 100 60 10000
И смысл тут в том, что сохранение происходит: раз в час, если было хотя бы 1 изменение, раз 5 минут, если было 100 изменений и раз в минуту если было 10000 изменений

2024-07-31 08:50 UTC, CaptainCuriousity commented on configure_proxy/configure_proxy.c
> +            char* token;
Коммент написал. Хранит текущую подстроку. В случае с save 3600 1 300 100 60 10000 он будет хранить сначала '3600', потом '1', потом '300' и т.д.

2024-07-31 08:55 UTC, CaptainCuriousity commented on configure_proxy/configure_proxy.c
> +                    current_data.saving_period = atoi(token);
Написал. save принимает ещё и количество необходимых изменений (и таких пар у save может быть несколько)

2024-07-31 08:55 UTC, CaptainCuriousity commented on configure_proxy/configure_proxy.h
> +struct SnapshotData {
Уже писал

2024-07-31 08:59 UTC, bezdnov commented on work_with_db/work_with_db.c
>      if (!strcmp(PQgetvalue(res, 0, 0), "f"))
Такое соглашение у команды exist(), см документацию. Коммент по теме написал.

2024-07-31 09:00 UTC, CaptainCuriousity commented on configure_proxy/configure_proxy.h
>  struct ProxyConfiguration {
Добавил коммент.

2024-07-31 09:00 UTC, CaptainCuriousity commented on configure_proxy/configure_proxy.h
> +extern ProxyConfiguration config;
Кстати, такой коммент уже есть. Но если есть необходимость, я могу удалить эту строку и просто добавить get_configuration() туда, где это нужно.

2024-07-31 09:01 UTC, CaptainCuriousity commented on configure_proxy/configure_proxy.h
> +extern ProxyConfiguration config;
*такая функция
Но всё работает и без неё, она просто не используется

2024-07-31 09:06 UTC, CaptainCuriousity commented on redis_reqv_converter/redis_reqv_converter.c
> +// error sizes are different, but in general case they are not larger than 256.
Константы вынес в .h

2024-07-31 09:07 UTC, CaptainCuriousity commented on work_with_db/work_with_db.c
> +    // if (config.loglevel >= LOG_VERBOSE) ereport(LOG, errmsg("start work with db"));
Убрал

2024-07-31 09:16 UTC, CaptainCuriousity commented on postgres_reqv_converter/postgres_reqv_converter.c
> +int
Коммент по теме добавил. Есть, оказывается, другие ошибки, типа -WRONGTYPE, но нам их поддерживать не надо.

2024-07-31 09:34 UTC, merged